# Generated by Django 3.1.3 on 2020-11-28 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos\\%y\\%m\\%d')),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.BooleanField(default=False)),
                ('description', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
