# Generated by Django 3.1.3 on 2020-11-28 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='state',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='zipcode',
            new_name='is_mvp',
        ),
        migrations.AddField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
